export const GET_CHARACTERS_FETCHING = 'GET_CHARACTERS_FETCHING';
export const GET_CHARACTERS_FULFILLED = 'GET_CHARACTERS_FULFILLED';
export const GET_CHARACTERS_REJECTED = 'GET_CHARACTERS_REJECTED';

export const ADD_CHARACTERS_FETCHING = 'ADD_CHARACTERS_FETCHING';
export const ADD_CHARACTERS_FULFILLED = 'ADD_CHARACTERS_FULFILLED';
export const ADD_CHARACTERS_REJECTED = 'ADD_CHARACTERS_REJECTED';

export const DELETE_CHARACTERS_FETCHING = 'DELETE_CHARACTERS_FETCHING';
export const DELETE_CHARACTERS_FULFILLED = 'DELETE_CHARACTERS_FULFILLED';
export const DELETE_CHARACTERS_REJECTED = 'DELETE_CHARACTERS_REJECTED';