export const REQUEST_CHARACTERS = 'REQUEST_CHARACTERS';
export const RECEIVE_CHARACTERS = 'RECEIVE_CHARACTERS';
export const FAILURE_CHARACTERS = 'FAILURE_CHARACTERS';

export const REQUEST_ADD_CHARACTER = 'REQUEST_NEW_CHARACTER';
export const RECEIVE_ADD_CHARACTER = 'RECEIVE_NEW_CHARACTER';
export const FAILURE_ADD_CHARACTER = 'FAILURE_NEW_CHARACTER';

export const REQUEST_DELETE_CHARACTER = 'REQUEST_DELETE_CHARACTER';
export const RECEIVE_DELETE_CHARACTER = 'RECEIVE_DELETE_CHARACTER';
export const FAILURE_DELETE_CHARACTER = 'FAILURE_DELETE_CHARACTER';